# Generated by Django 2.1.10 on 2020-08-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='devops_name',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tiga_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
