WORDS = {
    "Vlv": "Valve",
    "Nitro": "Nitrogen",
    "Botl": "Bottle",
    "Psi": "Pressure",
    "PSI": "Pressure",
    "Sta": "Station",
    "Incom": "Incoming",
    "Prvr": "Prover",
    "Mtr": "Meter",
    "MTR": "Meter",
    "Fact": "Factor",
    "Tk": "Tank",
    "Pwr": "Power",
    "Bldg": "Building",
    "Temp": "Temperature",
    "Sig": "Signal",
    "Suct": "Suction",
    "Stpt": "Setpoint",
    "Fbk": "Feedback",
    "Vol": "Volume",
    "Chrgr": "Charger",
    "Btry": "Battery",
    "Vibr": "Vibration",
    "HiHi": "High-High",
    "LoLo": "Low-Low",
    "Lo": "Low",
    "Hi": "High",
    "Xmitr": "Transmitter",
    "Diff": "Differential",
    "Stnr": "Strainer",
    "Berng": "Bearing",
    "Disc": "Discharge",
    "Inj": "Injection",
    "Brkr": "Breaker",
    "Accum": "Accumulator",
    "Avg": "Average",
    "Num": "Number",
    "Pos": "Position",
    "Comm": "Communication",
    "Prog": "Progress",
    "Mani": "Manifold",
    "Avail": "Available",
    "Bstr": "Booster",
    "Mltln": "Multilin",
    "Strnr": "Strainer",
    "Cabnt": "Cabinet",
    "Del": "Delivery",
    "Lvl": "Level",
    "LVL": "Level",
    "PWR": "Power",
    "Byp": "Bypass",
    "Fac": "Facility",
    "VLV": "Valve",
    "CV": "Control Valve",
    "L/O": "Lockout",
    "S/D": "Shutdown",
    "ESD": "Emergency Shutdown",
    "GC": "Gas Chromatograph",
    "GPH": "Gallons Per Hour",
    "GSV": "Gross Standard Volume",
    "H2S": "Hydrogen Sulfide",
    "IV": "Indicated Volume",
    "KO": "Knockout",
    "LEL": "Lower Explosive Limit",
    "M/L": "Mainline",
    "NSV": "Net Standard Volume",
    "PPM": "Parts Per Million",
    "RV": "Relief Valve",
    "UPS": "Uninterrupted Power Supply",
    "VP": "Vapor Pressure",
    "Upstrm": "Upstream",
    "Dnstrm": "Downstream"
}

WORDS_UPPER = {
    "VLV": "Valve",
    "NITRO": "Nitrogen",
    "BOTL": "Bottle",
    "PSI": "Pressure",
    "STA": "Station",
    "INCOM": "Incoming",
    "PRVR": "Prover",
    "MTR": "Meter",
    "FACT": "Factor",
    "TK": "Tank",
    "PWR": "Power",
    "BLDG": "Building",
    "TEMP": "Temperature",
    "SIG": "Signal",
    "SUCT": "Suction",
    "STPT": "Setpoint",
    "FBK": "Feedback",
    "VOL": "Volume",
    "CHRGR": "Charger",
    "BTRY": "Battery",
    "VIBR": "Vibration",
    "HIHI": "High-High",
    "LOLO": "Low-Low",
    "LO": "Low",
    "HI": "High",
    "XMITR": "Transmitter",
    "DIFF": "Differential",
    "STNR": "Strainer",
    "BERNG": "Bearing",
    "DISC": "Discharge",
    "INJ": "Injection",
    "BRKR": "Breaker",
    "ACCUM": "Accumulator",
    "AVG": "Average",
    "NUM": "Number",
    "POS": "Position",
    "COMM": "Communication",
    "PROG": "Progress",
    "MANI": "Manifold",
    "AVAIL": "Available",
    "BSTR": "Booster",
    "MLTLN": "Multilin",
    "STRNR": "Strainer",
    "CABNT": "Cabinet",
    "DEL": "Delivery",
    "LVL": "Level",
    "BYP": "Bypass",
    "FAC": "Facility",
    "CV": "Control Valve",
    "L/O": "Lockout",
    "S/D": "Shutdown",
    "ESD": "Emergency Shutdown",
    "GC": "Gas Chromatograph",
    "GPH": "Gallons Per Hour",
    "GSV": "Gross Standard Volume",
    "H2S": "Hydrogen Sulfide",
    "IV": "Indicated Volume",
    "KO": "Knockout",
    "LEL": "Lower Explosive Limit",
    "M/L": "Mainline",
    "NSV": "Net Standard Volume",
    "PPM": "Parts Per Million",
    "RV": "Relief Valve",
    "UPS": "Uninterrupted Power Supply",
    "VP": "Vapor Pressure",
    "UPSTRM": "Upstream",
    "DNSTRM": "Downstream",
    "PRES": "Pressure",
    "VSP": "Variable Setpoint"
}