# Generated by Django 2.2.2 on 2019-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='file',
            field=models.FilePathField(path='media/dds'),
        ),
    ]
