# Generated by Django 2.2.2 on 2019-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190621_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='file',
            field=models.FileField(upload_to='dds/'),
        ),
    ]
