# Generated by Django 2.2.2 on 2019-06-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20190621_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtf',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='dds',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
